"""Steward: analyzes failures and proposes amendments. Cannot promote."""
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.governance.models import AmendmentStatus, TargetType
from app.governance.registry import RuntimeRegistry


class FailurePattern(BaseModel):
    """A detected failure pattern from telemetry."""
    id: str
    description: str
    frequency: int
    affected_tasks: List[str] = Field(default_factory=list)
    severity: float = 0.5  # 0.0 to 1.0
    first_seen: datetime = Field(default_factory=datetime.utcnow)
    last_seen: datetime = Field(default_factory=datetime.utcnow)
    runtime_versions_affected: List[str] = Field(default_factory=list)
    failure_class: str = "unknown"
    regression_case: Dict[str, Any] = Field(default_factory=dict)


class Hypothesis(BaseModel):
    """An improvement hypothesis generated by the steward."""
    id: str
    description: str
    target: TargetType
    expected_improvement: str = ""
    rationale: str = ""
    supporting_evidence: List[str] = Field(default_factory=list)
    confidence: float = 0.5  # 0.0 to 1.0


class AmendmentProposal(BaseModel):
    """A steward-generated amendment proposal."""
    id: str
    parent_version: str

    target: TargetType
    description: str
    rationale: str

    proposed_diff: Dict[str, Any]

    hypotheses: List[Hypothesis] = Field(default_factory=list)

    evidence: List[Any] = Field(default_factory=list)
    evaluation: Optional[Any] = None

    status: AmendmentStatus = AmendmentStatus.PROPOSED

    proposer: str = "steward"
    created_at: datetime = Field(default_factory=datetime.utcnow)

    reviewer: Optional[str] = None
    decision: Optional[Any] = None

    resulting_runtime: Optional[str] = None


class Steward:
    """Analyzes failures, telemetry, and generates improvement hypotheses.

    The Steward is creative but not authoritative: it can propose changes,
    but it cannot unilaterally enact them.
    """

    MIN_FAILURE_FREQUENCY = 3

    def __init__(self, registry: RuntimeRegistry, constitution=None):
        self.registry = registry
        self.constitution = constitution
        self.failure_patterns: List[FailurePattern] = []
        self.hypotheses: List[Hypothesis] = []

    def analyze_telemetry(self, telemetry_data: List[Dict[str, Any]]) -> List[FailurePattern]:
        """Analyze telemetry to find recurring failure patterns."""
        patterns = []

        task_failures: Dict[str, List[Dict[str, Any]]] = {}
        for record in telemetry_data:
            task_id = record.get("task_id", "unknown")
            success = record.get("success", False)
            errors = record.get("errors", [])

            if not success or errors:
                task_failures.setdefault(task_id, []).append({
                    "runtime_version": record.get("runtime_version", "unknown"),
                    "errors": errors,
                    "input": record.get("input", {}),
                    "output": record.get("output"),
                    "failure_class": record.get("failure_class") or "incorrect_or_incomplete_output",
                })

        for task_id, failures in task_failures.items():
            if len(failures) >= self.MIN_FAILURE_FREQUENCY:
                pattern = FailurePattern(
                    id=f"pattern-{task_id}",
                    description=f"Repeated failure on task {task_id}",
                    frequency=len(failures),
                    affected_tasks=[task_id],
                    severity=0.7,
                    runtime_versions_affected=[f["runtime_version"] for f in failures],
                    failure_class=failures[0]["failure_class"],
                    regression_case={
                        "id": f"regression-{task_id}",
                        "type": "telemetry_replay",
                        "input": failures[0]["input"],
                        "expected_output": failures[0]["output"],
                        "failure_class": failures[0]["failure_class"],
                    },
                )
                patterns.append(pattern)

        self.failure_patterns.extend(patterns)
        return patterns

    def generate_hypothesis(self, pattern: FailurePattern, target: TargetType) -> Hypothesis:
        """Generate an improvement hypothesis based on a failure pattern."""
        hypothesis = Hypothesis(
            id=f"hyp-{pattern.id}-{target.value}",
            description=f"Improve handling for: {pattern.description}",
            target=target,
            expected_improvement="Reduced failure rate, improved correctness",
            rationale=f"Based on {pattern.frequency} repeated failures "
                      f"in runtime(s) {sorted(set(pattern.runtime_versions_affected))}",
            supporting_evidence=[pattern.id],
            confidence=0.6,
        )
        self.hypotheses.append(hypothesis)
        return hypothesis

    def propose_amendment(
        self,
        hypothesis: Hypothesis,
        target_component: str,
        description: str,
        rationale: str,
        proposed_diff: Dict[str, Any],
    ) -> AmendmentProposal:
        """Create an amendment proposal from a hypothesis (PROPOSED state only)."""
        proposal_id = f"prop-{hypothesis.id}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"

        current_runtime = self.registry.get_current()
        parent_version = current_runtime.version if current_runtime else "v0"

        return AmendmentProposal(
            id=proposal_id,
            parent_version=parent_version,
            target=hypothesis.target,
            description=description,
            rationale=rationale,
            proposed_diff=proposed_diff,
            hypotheses=[hypothesis],
        )

    def recommend_amendments(self, telemetry_data: List[Dict[str, Any]]) -> List[AmendmentProposal]:
        """Full steward loop: analyze telemetry and propose amendments."""
        proposals = []

        patterns = self.analyze_telemetry(telemetry_data)

        for pattern in patterns:
            for target in [TargetType.PROMPT, TargetType.MEMORY]:
                hypothesis = self.generate_hypothesis(pattern, target)
                proposal = self.propose_amendment(
                    hypothesis=hypothesis,
                    target_component=target.value,
                    description=f"Fix for: {pattern.description}",
                    rationale=pattern.description,
                    proposed_diff={
                        "target_component": target.value,
                        "change_description": pattern.description,
                        "regression_case": pattern.regression_case,
                        "failure_class": pattern.failure_class,
                    },
                )
                proposals.append(proposal)

        return proposals
